title: "GitHub Pages テスト"
description: "Jekyll のデフォルトテーマMinima を使用した、シンプルな構成のGitHub Pages のテストです。"
lang: "ja"

baseurl: /PagesTest

minima:
  social_links:
    - title: This repository at GitHub
      icon: github
      url: "https://github.com/uranuno/PagesTest"

remote_theme: "jekyll/minima@1722fcf"

plugins:
 - jekyll-feed
